name: Publish Homey App
on:
  workflow_dispatch:
  push:
    tags:
      - v**

jobs:
  main:
    name: Publish Homey App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: abn/github-action-homey-app/setup@main

      - uses: abn/github-action-homey-app/publish@main
        id: publish
        with:
          personal_access_token: ${{ secrets.HOMEY_PAT }}
