name: Update Homey App Version
on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: Version
        required: true
        default: patch
        options:
          - major
          - minor
          - patch
      changelog:
        type: string
        description: Changelog
        required: true

# Needed in order to push the commit and create a release
permissions:
  contents: write

jobs:
  main:
    name: Update Homey App Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: abn/github-action-homey-app/setup@main

      - uses: abn/github-action-homey-app/version@main
        id: version-update
        with:
          changelog: "${{ inputs.changelog }}"
          next: "${{ inputs.version }}"

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: ".homeychangelog.json .homeycompose/app.json app.json"
          commit_message: "Update Homey App Version to v${{ steps.version-update.outputs.new-version }}"

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: "v${{ steps.version-update.outputs.new-version }}"
          generateReleaseNotes: true
          makeLatest: true

      - uses: abn/github-action-homey-app/publish@main
        id: publish
        with:
          personal_access_token: ${{ secrets.HOMEY_PAT }}
